version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800

  qa-api:
    build: qa-api
    image: qa-api
    restart: "no"
    volumes:
      - ./qa-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  qa-ui:
    build: qa-ui
    image: qa-ui
    restart: "no"
    volumes:
      - ./qa-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3001
    depends_on:
      - qa-api

  llm-api:
    build:
      context: llm-api
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}  
    image: llm-api
    restart: "no"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    expose:
      - 7000

  database:
    container_name: database-server-dab-p2-4f39a9d5-9b37-4b13-b7d4-5693677e9d48
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
      
  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests